name: PerfAI Actions
description: Active Performance for APIs (public, mobile, & web)
author: PerfAI, Inc.
branding:
  icon: activity
  color: blue
      
inputs:
  apiSpecURL:
    description: OpenAPI-Specification/Swagger URL
    required: true
  apiBasePath:
    description: API Base Path
    required: true
  authUrl:
    description: Token Authentication URL
    required: true
  authBody:
    description: Authentication Body JSON/Data
    required: true
  licenseKey:
    description: A code or token that allows the user to identify him/herself as a legal customer 
    required: false
    
outputs:
  report:
    description: Displays performance report

runs:
  using: "composite"
  steps:
    - run: docker run --rm -e apiSpecURL=${{ inputs.apiSpecURL }} -e apiBasePath=${{ inputs.apiBasePath }} -e authUrl=${{ inputs.authUrl }} -e authBody=${{ inputs.authBody }} -e licenseKey=${{ inputs.licenseKey }} ghcr.io/perfai-inc/perfai-engine:main
      shell: bash
